// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://fyf7c66nxrbnvheryktunegia4.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",

  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-nowio5tsofb7lng6tnisqosj7q"
};

export default awsmobile;
